# Generated by Django 3.0.14 on 2023-01-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='cuerpo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
