# Generated by Django 3.0.14 on 2023-01-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0002_auto_20230101_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='autor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
