# Generated by Django 3.0.14 on 2023-01-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0003_gimnasio_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='')),
                ('cuerpo', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='gimnasio',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='gimnasio',
            name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='gimnasio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='gimnasio',
            name='imagen',
        ),
    ]
