# Generated by Django 3.0.14 on 2023-01-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0004_auto_20230101_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='autor',
            field=models.CharField(max_length=60),
        ),
    ]
