# Generated by Django 3.0.14 on 2023-01-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0005_auto_20230101_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='cuerpo',
            field=models.CharField(max_length=150),
        ),
    ]
