# Generated by Django 4.1.5 on 2023-01-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0006_auto_20230101_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
