# Generated by Django 4.1.5 on 2023-01-17 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0007_alter_nutricion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
