# Generated by Django 4.1.5 on 2023-01-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0008_alter_nutricion_cuerpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutricion',
        ),
    ]
