# Generated by Django 4.1.5 on 2023-01-17 19:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_gym', '0009_delete_nutricion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
