# Generated by Django 3.0.14 on 2023-01-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_logueo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='')),
                ('cuerpo', models.CharField(max_length=150)),
            ],
        ),
    ]
