# Generated by Django 3.0.14 on 2023-01-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_logueo', '0002_nutricion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
