# Generated by Django 4.1.5 on 2023-01-17 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_logueo', '0003_auto_20230102_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
