# Generated by Django 4.1.5 on 2023-01-17 15:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_logueo', '0004_alter_nutricion_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
