# Generated by Django 4.1.5 on 2023-01-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_logueo', '0005_alter_nutricion_cuerpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricion',
            name='imagen',
        ),
    ]
