# Generated by Django 4.1.5 on 2023-01-18 19:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_logueo', '0006_remove_nutricion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
